name: License Scan
on: [push]
jobs:
  license-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@v2.2
        with:
          version: 7
          blackduck.url: ${{ secrets.BLACKDUCK_URL }}
          blackduck.api.token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          args: >
            --blackduck.trust.cert=true
            --detect.project.tags=VSE,PLS,DOE
            --detect.policy.check.fail.on.severities="BLOCKER"
            --detect.npm.include.dev.dependencies=false
            --detect.detector.search.exclusion=dist,coverage,node_modules
